import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";
import { resolveSafe, ensureRootExists } from "@/lib/fs";

// Chunked upload protocol:
//   POST multipart/form-data with fields:
//     file       - the chunk blob
//     path       - destination directory (relative to ROOT_DIR)
//     filename   - final file name
//     chunkIndex - 0-based chunk index
//     totalChunks - total number of chunks
//
//     uploadId   - UUID generated by the client per upload session
//
// Server stores chunks in ROOT_DIR/.tmp/<filename>-<uploadId>/ (unique per session).
// On the last chunk it assembles and moves the file to destination.

export async function POST(req: NextRequest) {
  await ensureRootExists();

  const form = await req.formData();
  const file = form.get("file") as File | null;
  const clientDir = form.get("path") as string | null;
  const filename = form.get("filename") as string | null;
  const chunkIndex = parseInt(form.get("chunkIndex") as string, 10);
  const totalChunks = parseInt(form.get("totalChunks") as string, 10);
  const uploadId = form.get("uploadId") as string | null;

  if (!file || !clientDir || !filename || isNaN(chunkIndex) || isNaN(totalChunks) || !uploadId) {
    return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
  }

  // Sanitise filename: strip path separators so clients cannot write outside target dir
  const safeName = path.basename(filename);
  if (!safeName) return NextResponse.json({ error: "Invalid filename" }, { status: 400 });

  try {
    const destDir = resolveSafe(clientDir);
    await fs.mkdir(destDir, { recursive: true });

    // Temp staging area — keyed by uploadId so each upload session gets its own
    // directory. This prevents chunk collisions between retries or concurrent
    // uploads of the same filename.
    const { ROOT_DIR } = await import("@/lib/fs");
    const tmpDir = path.join(ROOT_DIR, ".tmp", `${safeName}-${uploadId}`);
    await fs.mkdir(tmpDir, { recursive: true });

    // Write this chunk
    const chunkPath = path.join(tmpDir, `chunk-${chunkIndex}`);
    const buffer = Buffer.from(await file.arrayBuffer());
    await fs.writeFile(chunkPath, buffer);

    console.log(`[upload] ${safeName} chunk ${chunkIndex + 1}/${totalChunks}`);

    // If last chunk, assemble
    if (chunkIndex === totalChunks - 1) {
      const finalPath = path.join(destDir, safeName);

      try {
        // Remove a pre-existing file so we don't inherit its permissions
        await fs.unlink(finalPath).catch(() => {});

        const fileHandle = await fs.open(finalPath, "w");
        try {
          let fileOffset = 0;
          for (let i = 0; i < totalChunks; i++) {
            const cp = path.join(tmpDir, `chunk-${i}`);
            const data = await fs.readFile(cp);
            // Use explicit position so assembly is correct regardless of any
            // implicit file-cursor state, and check for partial writes.
            const { bytesWritten } = await fileHandle.write(data, 0, data.length, fileOffset);
            if (bytesWritten !== data.length) {
              throw new Error(`Partial write at chunk ${i}: ${bytesWritten}/${data.length} bytes`);
            }
            fileOffset += bytesWritten;
          }
        } finally {
          await fileHandle.close();
        }
      } finally {
        // Always clean up tmp chunks
        await fs.rm(tmpDir, { recursive: true, force: true });
      }

      console.log(`[upload] ${safeName} assembled successfully → ${finalPath}`);
      return NextResponse.json({ ok: true, done: true });
    }

    return NextResponse.json({ ok: true, done: false });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[upload][CRITICAL] ${msg}`);
    if (msg.startsWith("[CRITICAL]")) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// App Router route handlers on the Node.js runtime have no imposed body size limit.
// (bodySizeLimit only applies to Server Actions via next.config serverActions.bodySizeLimit.)
// maxDuration guards against platform-level timeouts when assembling very large files.
export const maxDuration = 300;
